-- Run in Supabase SQL editor (Dashboard → SQL → New query)
-- Enables pgvector and creates the code embedding table + similarity RPC.

create extension if not exists vector;

create table if not exists public.code_embeddings (
  id bigint generated by default as identity primary key,
  repo text not null,
  path text not null,
  chunk_index integer not null default 0,
  content_hash text not null,
  content text not null,
  source text not null default 'code',
  embedding vector(1536),
  updated_at timestamptz not null default now(),
  unique (repo, path, chunk_index, content_hash)
);

create index if not exists code_embeddings_repo_idx on public.code_embeddings (repo);
create index if not exists code_embeddings_embedding_idx
  on public.code_embeddings using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create or replace function public.match_code_embeddings(
  query_embedding vector(1536),
  match_repo text,
  match_count integer,
  match_threshold double precision default 0.55
)
returns table (
  path text,
  content text,
  similarity double precision,
  source text
)
language sql stable
as $$
  select
    ce.path,
    ce.content,
    1 - (ce.embedding <=> query_embedding) as similarity,
    ce.source
  from public.code_embeddings ce
  where ce.repo = match_repo
    and ce.embedding is not null
    and 1 - (ce.embedding <=> query_embedding) >= match_threshold
  order by ce.embedding <=> query_embedding
  limit match_count;
$$;

-- Optional: allow service role full access (default in Supabase for service role)
-- alter table public.code_embeddings enable row level security;
