-- Harden embeddings table + finding outcome feedback loop (v0.5.4).

-- Enable RLS: service role only. Never query this table with the anon key.
alter table public.code_embeddings enable row level security;

drop policy if exists "service_role_all_code_embeddings" on public.code_embeddings;
create policy "service_role_all_code_embeddings" on public.code_embeddings
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- Optional outcome table: track resolved / dismissed findings to tune min_confidence over time.
create table if not exists public.review_finding_outcomes (
  id bigint generated by default as identity primary key,
  repo text not null,
  pr_number integer not null,
  commit_sha text,
  finding_title text not null,
  finding_file text,
  finding_line integer,
  severity text,
  category text,
  confidence double precision,
  agent text,
  outcome text not null check (outcome in ('resolved', 'dismissed', 'thumbs_up', 'thumbs_down')),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists review_finding_outcomes_repo_idx
  on public.review_finding_outcomes (repo, created_at desc);

alter table public.review_finding_outcomes enable row level security;

drop policy if exists "service_role_all_outcomes" on public.review_finding_outcomes;
create policy "service_role_all_outcomes" on public.review_finding_outcomes
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
